sudo: false
language: ruby
cache: bundler
rvm:
  - jruby
  - 2.3.1
  - rubinius-3.84
  - rbx
  - rbx-2
  - rbx-3
  - rubinius
  - rubinius-2
  - rubinius-3
before_install:
  - gem update bundler
  - gem cleanup bundler
install: "bundle install --jobs 8"
script: "bundle exec rake"
gemfile:
  - gemfiles/5.1.gemfile
matrix:
  fast_finish: true
branches:
  only:
    - master
