sudo: false
language: ruby
cache: bundler
rvm:
  - rbx-3
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
script: "bundle exec rake"
gemfile:
  - gemfiles/5.1.gemfile
matrix:
  fast_finish: true
branches:
  only:
    - master
