sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.3
  - jruby
  - jruby-head
  - rbx
  - rbx-2
  - rbx-3
  - rbx-head
  - rubinius
  - rubinius-2
  - rubinius-3
  - rubinius-head
script: "bundle exec rake"
gemfile:
  - gemfiles/5.1.gemfile
matrix:
  fast_finish: true
branches:
  only:
    - master
